# Generated by Django 4.2.23 on 2025-07-03 02:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Full street address', null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_emergency',
            field=models.CharField(blank=True, help_text='Another phone number in case of emergency', max_length=20, null=True, verbose_name='emergency contact phone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_landline',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='landline phone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile phone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.png', null=True, upload_to=users.models.user_directory_path, verbose_name='profile picture'),
        ),
    ]
