# Generated by Django 4.2.23 on 2025-07-03 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='medication name')),
                ('dosage', models.CharField(blank=True, help_text='e.g., 10mg, 2 tablets, 5ml', max_length=100, null=True, verbose_name='dosage')),
                ('frequency', models.CharField(blank=True, help_text='e.g., Once daily, Twice a day, Every other day', max_length=255, null=True, verbose_name='frequency')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the medication', null=True, verbose_name='notes')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Date medication was stopped, if applicable', null=True, verbose_name='end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is the user currently taking this medication?', verbose_name='is currently active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'medication',
                'verbose_name_plural': 'medications',
                'ordering': ['-is_active', 'name'],
                'unique_together': {('user', 'name', 'dosage', 'frequency')},
            },
        ),
    ]
