# pyproject.toml
[tool.black]
line-length = 88 # Or 79, 100, 120, etc.
target-version = ['py39', 'py310', 'py311', 'py312'] # Specify the Python versions you target
include = '\.pyi$|\.py$' # Only format .py and .pyi files
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.env
  | \_build
  | buck-out
  | build
  | dist
  | migrations
)/
'''