# Generated by Django 4.2.23 on 2025-06-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (e.g., kg or lbs. Please use consistent units, e.g., 75.50)', max_digits=5, null=True),
        ),
    ]
