# Generated by Django 4.2.23 on 2025-06-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measurement_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height (e.g., in meters: 1.75 or in cm: 175.00)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (e.g., kg or lbs, specify units consistently)', max_digits=5, null=True),
        ),
    ]
