# Generated by Django 4.2.23 on 2025-07-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_measurement_height_alter_measurement_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height (e.g., in meters: 1.75 or in cm: 175.00 - if in cm, remember to divide by 100 for BMI)', max_digits=4, null=True),
        ),
    ]
